name: Trigger auto deployment for ansalemo-gh-actions-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ansalemo-gh-actions-test-AutoDeployTrigger-98ad8c10-1ff0-4aa3-9085-d25cd686b96a.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ansalemocontainerregistry.azurecr.io
          username: ${{ secrets.ANSALEMOGHACTIONSTEST_REGISTRY_USERNAME }}
          password: ${{ secrets.ANSALEMOGHACTIONSTEST_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ansalemocontainerregistry.azurecr.io/ansalemo-gh-actions-test:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ANSALEMOGHACTIONSTEST_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ansalemo-gh-actions-test -g ansalemo-rg --server ansalemocontainerregistry.azurecr.io --username  ${{ secrets.ANSALEMOGHACTIONSTEST_REGISTRY_USERNAME }} --password ${{ secrets.ANSALEMOGHACTIONSTEST_REGISTRY_PASSWORD }}
            az containerapp update -n ansalemo-gh-actions-test -g ansalemo-rg --image ansalemocontainerregistry.azurecr.io/ansalemo-gh-actions-test:${{ github.sha }}
